let features = new Map();
features.set('brand', null);
features.set('model', null);
features.set('owner', null);
features.set('sn', null);
features.set('mac', null);
features.set('type', new Set(['location', 'case', 'motherboard', 'cpu', 'graphics-card', 'ram', 'hdd', 'odd', 'psu', 'audio-card', 'network-card', 'monitor', 'mouse', 'keyboard', 'switch', 'hub', 'modem-router', 'fdd', 'ports-bracket', 'other-card', 'heatsink', 'fan', 'fan-controller']));
features.set('working', new Set(['no', 'yes', 'maybe']));
features.set('capacity-byte', null);
features.set('frequency-hertz', null);
features.set('diameter-mm', null);
features.set('diagonal-inch', null);
features.set('has-gpu', new Set(['no', 'yes']));
features.set('color', new Set(['black', 'white', 'green', 'yellow', 'red', 'blue', 'grey', 'darkgrey', 'lightgrey', 'pink', 'transparent', 'brown', 'orange', 'violet', 'sip-brown', 'lightblue']));
features.set('motherboard-form-factor', new Set(['atx', 'miniatx', 'microatx', 'miniitx', 'proprietary', 'btx', 'flexatx']));
features.set('notes', null);
features.set('agp-sockets-n', null);
features.set('arrival-batch', null);
features.set('capacity-byte', null);
features.set('capacity-decibyte', null);
features.set('cib', null);
features.set('core-n', null);
features.set('cpu-socket', new Set(['other', 'other-slot', 'other-socket', 'other-dip', 'g1', 'g2', 'socket7', 'm', 'socket370', 'socket462a', 'socket423', 'socket478', 'socket603', 'socket754', 'socket940', 'socket939', 'lga775', 'lga771', 'am1', 'am2', 'am2plus', 'am3', 'am3plus', 'am4', 'fm1', 'fm2', 'fm2plus', 'lga1366', 'lga1156', 'g34', 'c32', 'lga1248', 'lga1567', 'lga1155', 'lga2011', 'lga1150', 'g3', 'lga1151', 'lga3647', 'lga2066']));
features.set('dvi-ports-n', null);
features.set('ethernet-ports-1000m-n', null);
features.set('ethernet-ports-100m-n', null);
features.set('ethernet-ports-10base2-n', null);
features.set('ethernet-ports-10m-n', null);
features.set('hdd-odd-form-factor', new Set(['5.25', '3.5', '2.5', '2.5slim', 'm2']));
features.set('ide-ports-n', null);
features.set('odd-type', new Set(['cd-r', 'cd-rw', 'dvd-r', 'dvd-rw', 'bd-r', 'bd-rw']));
features.set('pcie-power', new Set(['4pin', '6pin', '8pin']));
features.set('pcie-sockets-n', null);
features.set('pci-sockets-n', null);
features.set('power-connector', new Set(['other', 'other-barrell', '']));
features.set('power-idle-watt', null);
features.set('power-rated-watt', null);
features.set('ps2-ports-n', null);
features.set('psu-ampere', null);
features.set('psu-socket', new Set(['other', 'at', 'atx', 'atx-p4', 'atx-p4-extended', 'atx-p4-4pin', 'atx-p4-8pin', 'atx-p4-8pin']));
features.set('psu-volt', null);
features.set('ram-socket', new Set(['pc66', 'pc100', 'pc133', 'ddr', 'ddr2', 'ddr3', 'ddr4']));
features.set('sata-ports-n', null);
features.set('software', null);
features.set('usb-ports-n', null);
features.set('vga-ports-n', null);
features.set('windows-serial-number', null);
features.set('windows-serial-version', null);
features.set('soldered-in-place', new Set(['no', 'yes']));
features.set('power-idle-pfc', null);
features.set('firewire-ports-n', null);
features.set('serial-ports-n', null);
features.set('parallel-ports-n', null);
features.set('ram-form-factor', new Set(['dimm', 'so-dimm', 'minidimm', 'microdimm']));
